"""
Configuration module for LangGraph RAG service.
"""

from .settings import (
    OLLAMA_CHAT_API_URL,
    CHAT_MODEL,
    CHAT_TIMEOUT,
    RETRIEVAL_TOP_K,
    MAX_CONTEXT_LENGTH,
    ENABLE_CONVERSATION_HISTORY,
    MAX_HISTORY_LENGTH,
    SIMILARITY_THRESHOLD,
    COLLECTION_NAME,
    CHROMADB_PERSIST_DIRECTORY,
)

__all__ = [
    "OLLAMA_CHAT_API_URL",
    "CHAT_MODEL",
    "CHAT_TIMEOUT",
    "RETRIEVAL_TOP_K",
    "MAX_CONTEXT_LENGTH",
    "ENABLE_CONVERSATION_HISTORY",
    "MAX_HISTORY_LENGTH",
    "SIMILARITY_THRESHOLD",
    "COLLECTION_NAME",
    "CHROMADB_PERSIST_DIRECTORY",
]




